CREATE DATABASE IF NOT EXISTS `ToDoList` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `ToDoList`;

DROP TABLE IF EXISTS `list`;
CREATE TABLE IF NOT EXISTS `list` (
	`list_id` int(11) NOT NULL AUTO_INCREMENT,
	`list_name` varchar(50) DEFAULT NULL,
	`title` varchar(50) DEFAULT NULL,
	`description` text(8000000000) DEFAULT NULL,
	PRIMARY KEY (`Anime_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;